---

- name: Configure dovecot
  include_tasks: configure.yml
  tags:
    - role::dovecot
    - role::dovecot::configure

- name: Setup dovecot service
  include_tasks: service.yml
  tags:
    - role::dovecot
    - role::dovecot::service
