---
# Role handlers

- name: Reload dovecot daemon
  ansible.builtin.service:
    name: dovecot
    state: reloaded
  listen:
    - dovecot reload
  tags:
    - role::dovecot
    - role::dovecot::service
