---

- name: Prepare
  hosts: molecule_hosts
  gather_facts: no
  roles:
    - role: amtega.packages
      vars:
        packages_python:
          all:
            all:
              - pexpect: latest
        packages_os:
          all:
            all:
              socat: latest
  tasks:
    - name: Include role internal vars
      ansible.builtin.include_vars: ../../vars/main.yml

    - name: Add default mail folder to users
      ansible.builtin.file:
        path: /etc/skel/Mail
        state: directory
        mode: "0700"

    - name: Add default dovecot folder
      ansible.builtin.file:
        path: "{{ dovecot_config_dir }}"
        state: directory
        mode: "0750"

    - name: Create test group
      ansible.builtin.group:
        name: users
        state: present

    - name: Create test user
      ansible.builtin.user:
        name: "{{ test_user }}"
        password: "{{ test_pass | password_hash('sha512') }}"
        create_home: yes
        state: present
        group: users

    - name: Setup Postfix
      ansible.builtin.include_role:
        name: amtega.postfix
